version: '3.9'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: message_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  web:
    build:
      dockerfile: app/Dockerfile
    command: >
      sh -c "alembic upgrade head &&
      (uvicorn app.main:app --host 0.0.0.0 --port 8000 & 
      python -m app.services.telegram_bot)"
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      dockerfile: app/Dockerfile
    command: celery -A app.services.celery_tasks.celery_app worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
